server:
  port: 6080

---
spring:
  application:
    name: id-generator-dubbo-provider

---
dubbo:
  scan:
    base-packages: com.haozi.id.generator.dubbo.provider
  application:
    name: id-generator-provider
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo

---
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/idgenerator
    username: root
    password: root

#---
#spring:
#  redis:
#    host: 127.0.0.1
#    port: 6379

---
id:
  generator:
    one-request-id-max: 50
    dashboard: http://127.0.0.1:6082